#!/usr/bin/env bash

cabal-dev ghci -XFlexibleInstances -XRankNTypes -XDeriveGeneric -XCPP -XTemplateHaskell -XQuasiQuotes -XOverloadedStrings -XNoImplicitPrelude -XKindSignatures -XTypeFamilies -XFlexibleContexts -XGADTs -XMultiParamTypeClasses $*