Default: &defaults
  user: podly-server-hs
  password: podly-server-hs
  host: localhost
  database: podly-server-hs
  connections: 10

Development:
  host: ds043027.mongolab.com:43027
  database: heroku_app9312789
  user: heroku_app9312789
  password: nsg86264jmo61824h156p8u59m
  <<: *defaults

Testing:
  database: podly-server-hs_test
  <<: *defaults

Staging:
  database: podly-server-hs_staging
  connections: 100
  <<: *defaults

Production:
  database: podly-server-hs_production
  connections: 100
  host: ds043027.mongolab.com
  port: 43027
  database: heroku_app9312789
  user: heroku_app9312789
  password: nsg86264jmo61824h156p8u59m
  <<: *defaults
