Default: &defaults
  user: podly
  password: podly
  host: localhost
  port: 5432
  database: podly
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: podly-server-hs_test
  <<: *defaults

Staging:
  database: podly-server-hs_staging
  poolsize: 100
  <<: *defaults

Production:
  database: d9ao46d1elv9ms
  host: ec2-107-22-169-148.compute-1.amazonaws.com
  user: dojjqveidcdqeo
  password: EyCxsy55NYSha2FMn-5qMFkY-I
  poolsize: 100
  <<: *defaults