Default: &defaults
  user: podly
  password: podly
  host: localhost
  port: 5432
  database: podly
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: podly-server-hs_test
  <<: *defaults

Staging:
  database: podly-server-hs_staging
  poolsize: 100
  <<: *defaults

Production:
  database: d9si38dhr17rh
  host: ec2-184-73-164-26.compute-1.amazonaws.com
  user: u5hk9g9nqp86a3
  password: pedc2ppevecdqg80m2o8v7hlu0j
  port: 6182
  poolsize: 100
  <<: *defaults