Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  copyright:  © 2012 by Nerd Tribe
  mixpanel: fb9dacb040c67ca281bbd20b30809eb8
  amazonAffiliate: nerdtrcom-20

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://podly.co"
  port: 80
  googleAnalytics: UA-37496670-1
  # TODO - enable live metrics mixpanel: b0067de423831de083e85861614df4ba
  mixpanel: fb9dacb040c67ca281bbd20b30809eb8
  <<: *defaults
