Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  copyright:  © 2012 by Nerd Tribe

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://podly.co"
  port: 80
  analytics: UA-37496670-1
  <<: *defaults
